package com.carrie.lldiary.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "EMOJI_UPDATE_TIME".
 */
public class EmojiUpdateTime {

    private String objectId;
    private String url;
    private String path;
    private String name;
    private Integer status;
    private String updateAt;
    private String insertTime;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public EmojiUpdateTime() {
    }

    public EmojiUpdateTime(String objectId) {
        this.objectId = objectId;
    }

    public EmojiUpdateTime(String objectId, String url, String path, String name, Integer status, String updateAt, String insertTime) {
        this.objectId = objectId;
        this.url = url;
        this.path = path;
        this.name = name;
        this.status = status;
        this.updateAt = updateAt;
        this.insertTime = insertTime;
    }

    public String getObjectId() {
        return objectId;
    }

    public void setObjectId(String objectId) {
        this.objectId = objectId;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public String getPath() {
        return path;
    }

    public void setPath(String path) {
        this.path = path;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public String getUpdateAt() {
        return updateAt;
    }

    public void setUpdateAt(String updateAt) {
        this.updateAt = updateAt;
    }

    public String getInsertTime() {
        return insertTime;
    }

    public void setInsertTime(String insertTime) {
        this.insertTime = insertTime;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
