package com.carrie.lldiary.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

import android.os.Parcel;
import android.os.Parcelable;

/**
 * Entity mapped to table "MONEY".
 */
public class Money implements Parcelable {

    private Long id;
    /** Not-null value. */
    private String classifyIcon;
    /** Not-null value. */
    private String accountIcon;
    /** Not-null value. */
    private String classify;
    /** Not-null value. */
    private String account;
    /** Not-null value. */
    private String content;
    private String income;
    private String expense;
    private String price;
    private int state;
    /** Not-null value. */
    private String date;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Money() {
    }

    public Money(Long id) {
        this.id = id;
    }

    public Money(Long id, String classifyIcon, String accountIcon, String classify, String account, String content, String income, String expense, String price, int state, String date) {
        this.id = id;
        this.classifyIcon = classifyIcon;
        this.accountIcon = accountIcon;
        this.classify = classify;
        this.account = account;
        this.content = content;
        this.income = income;
        this.expense = expense;
        this.price = price;
        this.state = state;
        this.date = date;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getClassifyIcon() {
        return classifyIcon;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setClassifyIcon(String classifyIcon) {
        this.classifyIcon = classifyIcon;
    }

    /** Not-null value. */
    public String getAccountIcon() {
        return accountIcon;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setAccountIcon(String accountIcon) {
        this.accountIcon = accountIcon;
    }

    /** Not-null value. */
    public String getClassify() {
        return classify;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setClassify(String classify) {
        this.classify = classify;
    }

    /** Not-null value. */
    public String getAccount() {
        return account;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setAccount(String account) {
        this.account = account;
    }

    /** Not-null value. */
    public String getContent() {
        return content;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setContent(String content) {
        this.content = content;
    }

    public String getIncome() {
        return income;
    }

    public void setIncome(String income) {
        this.income = income;
    }

    public String getExpense() {
        return expense;
    }

    public void setExpense(String expense) {
        this.expense = expense;
    }

    public String getPrice() {
        return price;
    }

    public void setPrice(String price) {
        this.price = price;
    }

    public int getState() {
        return state;
    }

    public void setState(int state) {
        this.state = state;
    }

    /** Not-null value. */
    public String getDate() {
        return date;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDate(String date) {
        this.date = date;
    }

    // KEEP METHODS - put your custom methods here

    public String sign(int state){
       return state>0?"+":state<0?"-":"";
    }

    @Override
    public String toString() {
        return "Money{" +
                "account='" + account + '\'' +
                ", id=" + id +
                ", classifyIcon=" + classifyIcon +
                ", accountIcon=" + accountIcon +
                ", classify='" + classify + '\'' +
                ", content='" + content + '\'' +
                ", income='" + income + '\'' +
                ", expense='" + expense + '\'' +
                ", state=" + state +
                ", date='" + date + '\'' +
                ", price='" + price + '\'' +
                '}';
    }
    // KEEP METHODS END

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeValue(this.id);
        dest.writeString(this.classifyIcon);
        dest.writeString(this.accountIcon);
        dest.writeString(this.classify);
        dest.writeString(this.account);
        dest.writeString(this.content);
        dest.writeString(this.income);
        dest.writeString(this.expense);
        dest.writeString(this.price);
        dest.writeInt(this.state);
        dest.writeString(this.date);
    }

    protected Money(Parcel in) {
        this.id = (Long) in.readValue(Long.class.getClassLoader());
        this.classifyIcon = in.readString();
        this.accountIcon = in.readString();
        this.classify = in.readString();
        this.account = in.readString();
        this.content = in.readString();
        this.income = in.readString();
        this.expense = in.readString();
        this.price = in.readString();
        this.state = in.readInt();
        this.date = in.readString();
    }

    public static final Parcelable.Creator<Money> CREATOR = new Parcelable.Creator<Money>() {
        public Money createFromParcel(Parcel source) {
            return new Money(source);
        }

        public Money[] newArray(int size) {
            return new Money[size];
        }
    };
}
